openapi: 3.1.0
info: 
  title: Math API
  version: 1.0.0
  description: | 
    A math API with endpoints for addition, 
    substraction, multiplication and division
  
components:
  schemas:
    Operation:
      $ref: ./schemas/operation.yaml

paths:
  /add:
    $ref: ./paths/operation.yaml
  /substract:
    $ref: ./paths/operation.yaml
  /divide:
    $ref: ./paths/operation.yaml
  /multiply:
    $ref: ./paths/operation.yaml