openapi: 3.0.3
info: 
  title: Math API
  version: 1.0.0
  
components:
  schemas:
    Operation:
      $ref: ./schemas/operation.yaml

paths:
  /add:
    $ref: ./paths/operation.yaml
  /substract:
    $ref: ./paths/operation.yaml
  /divide:
    $ref: ./paths/operation.yaml
  /multiply:
    $ref: ./paths/operation.yaml